; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
lib_deps =
    https://github.com/jgromes/RadioLib#7.6.0
    SPI
    google/googletest@^1.12.1
test_build_src = yes
test_framework = googletest
monitor_filters = esp32_exception_decoder
extra_scripts = scripts/extra_script.py

[env:test_native]
platform = native
build_type = debug
build_flags =
    -DDEBUG
    -fsanitize=address,undefined
    -fno-sanitize=vptr
    -fno-omit-frame-pointer
    -g

[env:test_native_tsan]
platform = native
build_type = debug
build_flags =
    -DDEBUG
    -fsanitize=thread
    -fno-omit-frame-pointer
    -g

[env:test_native_profile]
platform = native
build_type = release
build_flags =
    -DDEBUG
    -fprofile-instr-generate
    -fcoverage-mapping
    -fno-omit-frame-pointer
    -g

[env:test_native_xray]
platform = native
build_type = release
build_flags =
    -DDEBUG
    -fxray-instrument
    -fxray-instruction-threshold=1
    -fno-omit-frame-pointer
    -g

[env:native]
platform = native

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11 -std=gnu++14 -std=gnu++17
build_flags =
    -DCONFIG_ESP_INT_WDT_TIMEOUT_MS=2000
    -DCONFIG_ESP_TASK_WDT_TIMEOUT_S=10
    -std=gnu++2a