name: Code Format Check

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Debug clang-format version
      run: clang-format --version
    
    - name: Check formatting
      run: |
        find . -name '*.cpp' -o -name '*.hpp' | xargs clang-format -style=file -i
        git diff --exit-code || (echo "Code formatting check failed!" && exit 1)