name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.x'
    
    # - name: Install PlatformIO
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install platformio

    # - name: Run Tests
    #   run: |
    #     platformio test -e native

    - name: Create build environment
      run: |
        mkdir build

    - name: Test build
      run: |
        cd build
        cmake --build . --target run_all_tests
